version: '3'

services:

  ## Auth-сервис

  auth_database:
    image: postgres:13.0
    restart: always
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/auth/.env.prod.db
    command: -p 6432
    ports:
      - 6432:6432

  auth_service:
    image: mistandok/auth-service:v2.0.2
    restart: always
    depends_on:
      - auth_database
      - auth_redis
      - refresh_auth_redis
    env_file:
      - ./config/auth/.env.prod
    ports:
      - 5100:5100

  auth_redis:
    image: redis:latest
    restart: always
    command: --port 6381
    expose:
      - 6381
    env_file:
      - ./config/auth/.env.prod

  refresh_auth_redis:
    image: redis:latest
    restart: always
    command: --port 6380
    expose:
      - 6380
    env_file:
      - ./config/auth/.env.prod

  rate_limit_redis:
    image: redis:latest
    restart: always
    command: --port 6382
    expose:
      - 6382
    env_file:
      - ./config/auth/.env.prod

  ## Billing-сервис

  billing:
    build:
      context: ../billing
      dockerfile: Dockerfile
    env_file:
      - ./config/billing/.env.prod
    volumes:
      - static_billing_volume:/opt/app/static
      - media_billing_volume:/opt/app/media
    expose:
      - 8100


  billing_db:
    image: postgres:13.0
    restart: always
    volumes:
      - billing_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./config/billing/.env.prod.db
    command: -p 7432
    ports:
      - 7432:7432


  ## Movie-сервис


  movie-admin:
    image: mikhailkushnerev/online-cinema-admin-panel:v2.0.5
    volumes:
      - static_volume:/opt/app/staticfiles
      - media_volume:/opt/app/mediafiles
    expose:
      - 8000
    env_file:
      - ./config/movie_admin/.env.prod
    depends_on:
      - movie-admin-db

  movie-admin-db:
    image: postgres:13.0
    volumes:
      - movie_admin_data:/var/lib/postgresql/data/
    command: -p 5432
    ports:
      - 5432:5432
    env_file:
      - ./config/movie_admin/.env.prod.db

  ## ETL-процессы

  etl-redis:
    image: redis:latest
    restart: always
    command: --port 6383
    ports:
      - 6383:6383

  etl-movie-billing:
    build:
      context: ../etl
      dockerfile: Dockerfile
    env_file:
      - ./config/etl/.env.prod
    depends_on:
      - billing_db
      - movie-admin-db
      - etl-redis
    restart: always

  ## Tests

  tests:
    build:
      context: ../tests/functional
      dockerfile: Dockerfile
    depends_on:
      - auth_database
      - auth_service
      - billing
      - billing_db
    env_file:
      - ./config/billing_functional_tests/.env.prod

volumes:
  static_volume:
  media_volume:

  auth_postgres_data:
  movie_admin_data:

  billing_postgres_data:
  media_billing_volume:
  static_billing_volume: